# Generated by Django 6.1.1 on 2026-09-14 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('insurance_expiry', 'Insurance Expiry'), ('license_expiry', 'License Expiry'), ('inspection_expiry', 'Inspection Expiry'), ('document_expiry', 'Document Expiry'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['is_read', '-created_at'],
            },
        ),
    ]
